---
title: "Brexit vote analysis"
author: Robin Penfold
date: 2016-10-12
categories:
  - politics
  - geo-viz
draft: false
preview: 2010_UK_blank_Election_Map.png
slug: brexit
description: |
  I wanted a better understanding of the Brexit vote and so thought I'd analyse it. 
  In this post, I therefore plot the Brexit vote and winning parliamentary party from 2016 by constituency, leaning heavily on the parlitools and ggiraph packages.
output:
  distill::distill_article:
    self_contained: false
    highlight: pygments
---

```{r brexit, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, layout="l-body-outset"}
suppressMessages(library(tidyverse))
library(ggiraph)
library(parlitools)
library(scales)

map_details <- west_hex_map

brexitData <- leave_votes_west %>% 
  mutate(
    `Leave Vote` = figure_to_use,
    `Party of MP` = as_factor(party_2016), 
    `Party of MP` = fct_lump(
      `Party of MP`,
      n = 7, 
      other_level = "Other")
    ) %>% 
  left_join(
    map_details,
    by = c("ons_const_id" = "gss_code")
    ) %>% 
  mutate(
    constituency = ifelse(
      is.na(constituency_name.x), 
      constituency_name.y, 
      constituency_name.x
      )
  ) %>% 
  select(constituency, `Leave Vote`, `Party of MP`, ons_const_id, geometry) %>% 
  mutate(
    `Party of MP` = 
      recode(
        `Party of MP`,
        `Scottish National Party` = "SNP", 
        `Liberal Democrat` = "LibDem"
        )
    ) %>% 
  arrange(constituency)

gg <- brexitData %>% 
  ggplot() + 
  geom_sf_interactive(
    aes(
      group = constituency,
      geometry = geometry,
      fill = `Leave Vote`,
      colour = `Party of MP`,
      tooltip = paste0(
        constituency, 
        "\n MP: ",
        `Party of MP`,
        "\n Leave vote: ",
        round(`Leave Vote` * 100, 0),
        "%"
        )
    )
  ) + 
  scale_fill_gradient2_interactive(
    low = "green", 
    mid = "white", 
    high = "orange", 
    midpoint = 0.5,
    labels = percent_format(accuracy = 1)
    ) +
  scale_colour_manual_interactive(
    values = c(
      Conservative = "#0087DC",
      DUP = "#D46A4C",
      Independent = "#6AB023",
      Other = "#AFAFAFAF",
      Labour = "#DC241F",
      LibDem = "#FDBB30",
      SNP = "#FFFF00",
      `Sinn Fein` = "#008800"
    )
  ) +
  theme_void() +
  labs(
    title = "Leave vote and winning party, by constituency", 
    subtitle = "Hover over a point for the details"
  ) + 
  theme(
    legend.position = "right",
    legend.text = element_text(size = 6, hjust = 0),
    legend.title = element_text(size = 8)
    )

girafe(ggobj = gg)
```

</br>

##   {.appendix}

For completeness (and reproducibility), here's the code that I used to calculate what's above.

```{r brexit, eval=FALSE, echo=TRUE}
```

## System settings {.appendix}

```{r, eval=TRUE, echo=FALSE}
sessionInfo()
```