baseurl = "https://www.p0bs.com/"
# baseurl = "/"
title = "Robin Penfold"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-gb"
# Enable comments by entering your Disqus shortname
disqusShortname = "p0bs"
enableEmoji = true
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-85616639-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.csv$", "\\.rds$", "_cache$"]
relativeurls = true

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "Data science, R, investment, sport and other geeky stuff"
  copyright = ""
  sidebarAbout = [
    "At work, I use investment techniques and data science to analyse asset managers.",
    "I also volunteer with DataKind to help charities to get more from their data.", 
    "Any free time is wasted on supporting sports teams that rarely win. "
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  # email = "you@yoursite.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""
  
  [[params.navlinks]]
  name = "Blog"
  url = "post/"
  
  [[params.navlinks]]
  name = "PremPredict"
  url = "prempredict/"
  
  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  email         = "robinpenfold@icloud.com"
  twitter       = "https://twitter.com/p0bs"
  stackoverflow = "https://stackoverflow.com/users/3588823/p0bs"
  linkedin      = "https://www.linkedin.com/in/robinpenfold/"