---
title: "Asset manager evaluation"
author: Robin Penfold
date: 2016-10-20
categories:
  - performance
  - presentations
draft: false
preview: evaluation.png
slug: evaluation
description: |
  Back in the day, I wrote research papers about investment practice. One example concerned how asset owners could better evaluate the investment performance of their asset managers. 
  As I still like the idea, I thought that I'd share it with you, given that the materials are already in the public domain. Basically, the idea is to view performance in the way that a Bayesian would.
output:
  distill::distill_article:
    self_contained: false
    highlight: pygments
---

The idea is pretty simple, which I'll outline below. If you want the details, check out [the formal paper, via SSRN](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2101771). For a more accessible introduction, I'd recommend the video below that was taken (and won an award) at the International Congress of Actuaries in 2014.

<p class="half-line">&nbsp;</p>

## The gist of the idea

In short, a key mantra of investment advisors is that asset owners should ignore the performance of their asset manager. Whether the manager has outperformed for you or not, it is claimed, is irrelevant to how you should expect them to perform in the future. However, a key idea in statistics, called Bayesian thinking, suggests the opposite: that you should use any new information you get about something to update your thinking on it. 

In this work, I therefore used Bayesian thinking to understand the advice that asset owners **should** get. It turns out that this advice makes common sense, particularly when paired with an understanding of whether the asset manager has some longer-term cyclicality in their performance.

And here's that video that I mentioned:

<p class="half-line">&nbsp;</p>

<iframe width="420" height="315" src="https://www.youtube.com/embed/xutu2axBa0o" frameborder="0"> </iframe>
